import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { DeliveryRouteMap } from "@/components/DeliveryRouteMap";
import { toast } from "sonner";

const statusLabel: Record<string, string> = { draft: "مسودة", ready: "جاهز", assigned: "مسند", picked_up: "تم الاستلام", en_route: "في الطريق", delivered: "تم التسليم", failed: "تعذر التسليم", returned: "عاد للفرع", cancelled: "ملغي" };
const canManage = (role?: string) => ["admin", "owner", "manager"].includes(role ?? "");

export default function DeliveryCenter() {
  const { user } = useAuth(); const manager = canManage(user?.role); const profile = trpc.profile.mine.useQuery();
  const branchId = profile.data?.employee?.branchId; const orders = trpc.delivery.list.useQuery({ branchId: branchId ?? 0 }, { enabled: manager && Boolean(branchId) });
  const mine = trpc.delivery.mine.useQuery(undefined, { enabled: !manager }); const summary = trpc.delivery.summary.useQuery({ branchId: branchId ?? 0 }, { enabled: manager && Boolean(branchId) }); const liveRoutes = trpc.delivery.liveRoutes.useQuery({ branchId: branchId ?? 0 }, { enabled: manager && Boolean(branchId), refetchInterval: 30_000 });
  const utils = trpc.useUtils(); const create = trpc.delivery.create.useMutation({ onSuccess: () => { toast.success("تم إنشاء طلب التوصيل."); orders.refetch(); } }); const assign = trpc.delivery.assign.useMutation({ onSuccess: () => orders.refetch() }); const update = trpc.delivery.updateStatus.useMutation({ onSuccess: () => { mine.refetch(); orders.refetch(); toast.success("تم تحديث حالة الطلب."); } }); const ping = trpc.delivery.pingLocation.useMutation();
  const team = trpc.employees.list.useQuery({ branchId: branchId ?? 0 }, { enabled: manager && Boolean(branchId) }); const policy = trpc.policies.attendance.useQuery({ branchId: branchId ?? 0 }, { enabled: manager && Boolean(branchId) }); const savePolicy = trpc.policies.saveAttendance.useMutation({ onSuccess: () => { policy.refetch(); toast.success("تم حفظ سياسة التأخير."); } });
  const [form, setForm] = useState({ orderCode: "", customerName: "", customerPhone: "", address: "", promisedAt: "" }); const [note, setNote] = useState<Record<number, string>>({}); const [policyForm, setPolicyForm] = useState({ graceMinutes: 15, lateMultiplier: 1, monthlyLateMinuteCap: "", pointsPerLateOccurrence: 0 });
  const displayed = manager ? orders.data ?? [] : (mine.data ?? []).map(order => ({ order, agentName: "" }));
  const active = useMemo(() => displayed.find(row => row.order.status === "en_route")?.order, [displayed]);
  useEffect(() => { if (!active || !navigator.geolocation) return; const id = navigator.geolocation.watchPosition(position => ping.mutate({ orderId: active.id, latitude: position.coords.latitude, longitude: position.coords.longitude, accuracyMeters: Math.round(position.coords.accuracy) }), () => undefined, { enableHighAccuracy: true, maximumAge: 30_000, timeout: 12_000 }); return () => navigator.geolocation.clearWatch(id); }, [active?.id]);
  const act = (orderId: number, status: "picked_up" | "en_route" | "delivered" | "failed" | "returned") => navigator.geolocation?.getCurrentPosition(p => update.mutate({ orderId, status, note: note[orderId], latitude: p.coords.latitude, longitude: p.coords.longitude, accuracyMeters: Math.round(p.coords.accuracy) }), () => update.mutate({ orderId, status, note: note[orderId] }));
  return <div className="space-y-6" dir="rtl"><section className="rounded-3xl bg-[#17344a] p-6 text-white shadow-xl"><p className="text-xs font-bold text-[#9ee4c9]">التوصيل المنزلي</p><h2 className="mt-1 text-2xl font-extrabold">رحلة واضحة للمندوب ولوحة متابعة فورية للإدارة</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-300">يعمل الموقع فقط أثناء رحلة نشطة، وتُسجل حالة الاستلام والتسليم والاستثناءات حتى عند عدم توفر GPS.</p></section>
    {manager ? <div className="grid gap-3 sm:grid-cols-4">{[["طلعات اليوم", summary.data?.dailyTrips], ["تم التسليم", summary.data?.delivered], ["متأخر", summary.data?.delayed], ["رحلات نشطة", summary.data?.active]].map(([label, value]) => <div key={String(label)} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-extrabold text-[#0f766e]">{value ?? "—"}</p></div>)}</div> : null}
    {manager ? <DeliveryRouteMap routes={liveRoutes.data ?? []} /> : null}
    {manager ? <><form className="grid gap-3 rounded-3xl border bg-white p-5 md:grid-cols-2" onSubmit={e => { e.preventDefault(); if (!branchId) return; create.mutate({ branchId, ...form, promisedAt: form.promisedAt ? new Date(form.promisedAt) : undefined }); }}><h3 className="md:col-span-2 font-extrabold">طلب توصيل جديد</h3>{[["كود الطلب","orderCode"],["اسم العميل","customerName"],["هاتف العميل","customerPhone"],["العنوان","address"]].map(([label,key]) => <div key={key}><Label>{label}</Label><Input required value={form[key as keyof typeof form]} onChange={e => setForm({ ...form, [key]: e.target.value })} /></div>)}<div><Label>موعد الوعد</Label><Input type="datetime-local" value={form.promisedAt} onChange={e => setForm({ ...form, promisedAt: e.target.value })} /></div><Button className="self-end bg-[#0f766e]">إنشاء وتجهيز الطلب</Button></form><form className="mt-4 grid gap-3 rounded-3xl border bg-white p-5 md:grid-cols-4" onSubmit={e => { e.preventDefault(); if (!branchId) return; savePolicy.mutate({ branchId, graceMinutes: Number(policyForm.graceMinutes), lateMultiplier: Number(policyForm.lateMultiplier), monthlyLateMinuteCap: policyForm.monthlyLateMinuteCap ? Number(policyForm.monthlyLateMinuteCap) : null, pointsPerLateOccurrence: Number(policyForm.pointsPerLateOccurrence) }); }}><h3 className="md:col-span-4 font-extrabold">سياسة التأخير القابلة للضبط</h3><Input type="number" min="0" placeholder={`سماحية بالدقائق (الحالي ${policy.data?.graceMinutes ?? 15})`} value={policyForm.graceMinutes} onChange={e => setPolicyForm({ ...policyForm, graceMinutes: Number(e.target.value) })}/><Input type="number" min="1" step="0.25" placeholder={`معامل الخصم (الحالي ${policy.data?.lateMultiplier ?? 1})`} value={policyForm.lateMultiplier} onChange={e => setPolicyForm({ ...policyForm, lateMultiplier: Number(e.target.value) })}/><Input type="number" min="1" placeholder="سقف دقائق الخصم شهرياً (اختياري)" value={policyForm.monthlyLateMinuteCap} onChange={e => setPolicyForm({ ...policyForm, monthlyLateMinuteCap: e.target.value })}/><Button type="submit">حفظ السياسة</Button></form></> : null}
    <section className="rounded-3xl border bg-white p-5"><h3 className="font-extrabold">{manager ? "طلبات الفرع" : "طلعاتي"}</h3><div className="mt-4 space-y-3">{displayed.map(({ order, agentName }) => <article key={order.id} className="rounded-2xl border border-slate-100 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold">{order.orderCode} · {order.customerName}</p><p className="mt-1 text-xs text-slate-500">{order.address} {agentName ? `· المندوب: ${agentName}` : ""}</p></div><Badge className="bg-[#e6f5ef] text-[#0f766e] hover:bg-[#e6f5ef]">{statusLabel[order.status]}</Badge></div>{manager && order.status === "ready" ? <div className="mt-3 flex gap-2"><select className="h-9 rounded-lg border px-2 text-sm" onChange={e => e.target.value && assign.mutate({ orderId: order.id, employeeId: Number(e.target.value) })}><option value="">تعيين مندوب…</option>{(team.data ?? []).map(member => <option key={member.id} value={member.id}>{member.fullName}</option>)}</select></div> : null}{!manager && !["delivered","failed","returned","cancelled"].includes(order.status) ? <div className="mt-3 flex flex-wrap gap-2"><Input className="max-w-xs" placeholder="ملاحظة أو إثبات التسليم عند الإغلاق" value={note[order.id] ?? ""} onChange={e => setNote({ ...note, [order.id]: e.target.value })} />{order.status === "assigned" ? <Button size="sm" onClick={() => act(order.id, "picked_up")}>استلام الطلب</Button> : null}{order.status === "picked_up" ? <Button size="sm" onClick={() => act(order.id, "en_route")}>بدء الرحلة</Button> : null}{order.status === "en_route" ? <><Button size="sm" onClick={() => act(order.id, "delivered")}>تم التسليم</Button><Button size="sm" variant="outline" onClick={() => act(order.id, "failed")}>تعذر التسليم</Button></> : null}</div> : null}</article>)}{!displayed.length ? <p className="py-8 text-center text-sm text-slate-500">لا توجد طلبات ضمن هذه القائمة.</p> : null}</div></section></div>;
}
