import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { downloadExcelWorkbook, mapEmployeeAuditToExcelRows } from "@/lib/excel-export";
import { ClipboardList, FileDown, History } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";

const actionLabels: Record<string, string> = { created: "إنشاء الملف", updated: "تعديل البيانات", archived: "أرشفة الملف", restored: "استعادة الملف" };
function formatDateTime(value?: Date | null) { return value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }

export default function EmployeeAuditLog() {
  const branches = trpc.organization.listBranches.useQuery();
  const [branchId, setBranchId] = useState(0);
  const [employeeId, setEmployeeId] = useState(0);
  const [auditSearch, setAuditSearch] = useState("");
  const [auditAction, setAuditAction] = useState<"created" | "updated" | "archived" | "restored" | "all">("all");
  const [auditFrom, setAuditFrom] = useState("");
  const [auditTo, setAuditTo] = useState("");
  const employees = trpc.employees.list.useQuery(branchId ? { branchId, includeArchived: true, sortBy: "name", sortDirection: "asc" } : undefined, { enabled: Boolean(branchId) });
  const auditInput = useMemo(() => ({ employeeId, action: auditAction === "all" ? undefined : auditAction, search: auditSearch.trim() || undefined, from: auditFrom ? new Date(`${auditFrom}T00:00:00`) : undefined, to: auditTo ? new Date(`${auditTo}T00:00:00`) : undefined }), [auditAction, auditFrom, auditSearch, auditTo, employeeId]);
  const audit = trpc.employees.auditLog.useQuery(auditInput, { enabled: Boolean(employeeId) });
  useEffect(() => { if (!branchId && branches.data?.[0]) setBranchId(branches.data[0].id); }, [branchId, branches.data]);
  useEffect(() => { if (!employeeId && employees.data?.[0]) setEmployeeId(employees.data[0].id); }, [employeeId, employees.data]);
  const changesFor = (row: unknown) => Array.isArray(row) ? row as Array<{ label?: string; before?: string | null; after?: string | null }> : [];
  const valueLabel = (value?: string | null) => value === null || value === undefined || value === "" ? "غير محدد" : value;
  const initialLoading = branches.isLoading || (Boolean(branchId) && employees.isLoading);
  const loadError = branches.error || employees.error || audit.error;
  const selectedEmployee = employees.data?.find(employee => employee.id === employeeId);
  const resetAuditFilters = () => { setAuditSearch(""); setAuditAction("all"); setAuditFrom(""); setAuditTo(""); };
  const exportAudit = () => {
    if (!selectedEmployee || !audit.data?.length) return;
    downloadExcelWorkbook("سجل-تدقيق-الموظف", ["الموظف", "الكود الوظيفي", "العملية", "منفذ العملية", "وقت العملية", "الحقل", "القيمة السابقة", "القيمة الجديدة"], mapEmployeeAuditToExcelRows(selectedEmployee.fullName, selectedEmployee.employeeCode, audit.data), "سجل التدقيق");
  };

  return <div dir="rtl" className="min-w-0 max-w-full space-y-6">
    <section className="flex flex-col items-stretch gap-4 rounded-[1.75rem] border border-[#dce9e2] bg-white p-5 shadow-[0_18px_42px_-34px_rgba(23,52,74,.45)] sm:flex-row sm:items-end sm:justify-between sm:p-6"><div className="min-w-0"><span className="rounded-full bg-[#e6f5ef] px-3 py-1 text-xs font-bold text-[#0f766e]">شفافية السجل</span><h2 className="mt-3 break-words text-2xl font-extrabold text-[#17344a]">سجل تعديلات الموظفين</h2><p className="mt-2 text-sm leading-7 text-slate-500">كل تعديل وأرشفة واستعادة يُسجل باسم المنفذ وتوقيته والحقول المتغيرة.</p></div><History className="h-10 w-10 shrink-0 self-end text-[#0f766e] sm:self-auto" /></section>
    <div className="grid gap-4 md:grid-cols-2"><label><span className="text-xs font-bold text-slate-600">الفرع</span><select aria-label="اختيار الفرع" disabled={branches.isLoading || Boolean(branches.error)} value={branchId || ""} onChange={event => { setBranchId(Number(event.target.value)); setEmployeeId(0); }} className="mt-1 h-10 w-full rounded-xl border border-[#d7e6df] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#0f766e] disabled:cursor-not-allowed disabled:bg-slate-50"><option value="" disabled>{branches.isLoading ? "جارٍ تحميل الفروع…" : "اختر الفرع"}</option>{branches.data?.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label><span className="text-xs font-bold text-slate-600">الموظف</span><select aria-label="اختيار الموظف" disabled={!branchId || employees.isLoading || Boolean(employees.error)} value={employeeId || ""} onChange={event => setEmployeeId(Number(event.target.value))} className="mt-1 h-10 w-full rounded-xl border border-[#d7e6df] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#0f766e] disabled:cursor-not-allowed disabled:bg-slate-50"><option value="" disabled>{employees.isLoading ? "جارٍ تحميل الموظفين…" : "اختر الموظف"}</option>{employees.data?.map(employee => <option key={employee.id} value={employee.id}>{employee.fullName} — {employee.employeeCode}</option>)}</select></label></div>
    <section className="rounded-2xl border border-[#dce9e2] bg-[#f8fcfa] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="font-extrabold text-[#17344a]">بحث وتصفية السجل</h3><p className="mt-1 text-xs text-slate-500">تُطبَّق الفلاتر على السجل المصرح به للموظف المختار، ويشمل التصدير النتائج الظاهرة فقط.</p></div><Button size="sm" variant="outline" onClick={exportAudit} disabled={!audit.data?.length || !selectedEmployee} className="shrink-0 border-[#b9d8ca] bg-white text-[#0f766e] hover:bg-[#eaf4ef] hover:text-[#0f766e]"><FileDown className="ml-1 h-3.5 w-3.5" />تصدير Excel</Button></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label><span className="text-xs font-bold text-slate-600">بحث</span><Input value={auditSearch} onChange={event => setAuditSearch(event.target.value)} placeholder="الحقل أو القيمة أو المنفذ" className="mt-1 h-10 border-[#d7e6df]" /></label><label><span className="text-xs font-bold text-slate-600">نوع العملية</span><select value={auditAction} onChange={event => setAuditAction(event.target.value as typeof auditAction)} className="mt-1 h-10 w-full rounded-xl border border-[#d7e6df] bg-white px-3 text-sm outline-none focus:ring-2 focus:ring-[#0f766e]"><option value="all">كل العمليات</option><option value="created">إنشاء الملف</option><option value="updated">تعديل البيانات</option><option value="archived">أرشفة الملف</option><option value="restored">استعادة الملف</option></select></label><label><span className="text-xs font-bold text-slate-600">من تاريخ</span><Input type="date" value={auditFrom} onChange={event => setAuditFrom(event.target.value)} className="mt-1 h-10 border-[#d7e6df]" /></label><label><span className="text-xs font-bold text-slate-600">إلى تاريخ</span><Input type="date" value={auditTo} onChange={event => setAuditTo(event.target.value)} className="mt-1 h-10 border-[#d7e6df]" /></label></div><Button size="sm" variant="ghost" onClick={resetAuditFilters} className="mt-3 text-[#0f766e] hover:bg-[#eaf4ef] hover:text-[#0f766e]">إعادة ضبط الفلاتر</Button></section>
    {initialLoading || audit.isLoading ? <Card><CardContent className="p-8 text-center text-sm font-bold text-[#0f766e]" aria-live="polite">جارٍ تحميل سجل التعديلات…</CardContent></Card> : loadError ? <Card className="border-rose-200 bg-rose-50"><CardContent className="grid min-h-52 place-items-center p-6 text-center"><div><ClipboardList className="mx-auto h-8 w-8 text-rose-600" /><h3 className="mt-3 font-extrabold text-rose-900">تعذر تحميل سجل التعديلات</h3><p className="mt-2 text-sm text-rose-700">تحقق من الاتصال، ثم أعد المحاولة. لم تُفقد أي بيانات.</p><Button size="sm" variant="outline" onClick={() => audit.refetch()} className="mt-4 border-rose-200 bg-white text-rose-700 hover:bg-rose-100 hover:text-rose-700">إعادة المحاولة</Button></div></CardContent></Card> : (audit.data?.length ?? 0) > 0 ? <div className="min-w-0 space-y-3">{audit.data?.map(log => <Card key={log.id} className="min-w-0 border-[#e1ece6] bg-white"><CardContent className="min-w-0 p-5"><div className="flex min-w-0 flex-wrap items-center justify-between gap-2"><div className="min-w-0"><p className="break-words font-extrabold text-[#17344a]">{actionLabels[log.action] || log.action}</p><p className="mt-1 break-words text-xs text-slate-500">بواسطة {log.actorName || "مستخدم النظام"} · {formatDateTime(log.createdAt)}</p></div><ClipboardList className="h-5 w-5 shrink-0 text-[#0f766e]" /></div>{changesFor(log.changes).length ? <div className="mt-4 min-w-0 divide-y divide-[#edf3ef] rounded-xl bg-[#f8fcfa] px-4">{changesFor(log.changes).map((change, index) => <div key={`${change.label}-${index}`} className="grid min-w-0 gap-1 py-3 text-sm md:grid-cols-[150px_1fr_1fr]"><span className="break-words font-bold text-[#17344a]">{change.label || "حقل"}</span><span className="break-words text-slate-500">السابق: {valueLabel(change.before)}</span><span className="break-words text-[#0f766e]">الجديد: {valueLabel(change.after)}</span></div>)}</div> : null}</CardContent></Card>)}</div> : <Card><CardContent className="grid min-h-52 place-items-center p-6 text-center"><div><ClipboardList className="mx-auto h-8 w-8 text-[#0f766e]" /><h3 className="mt-3 font-extrabold text-[#17344a]">لا توجد تعديلات تطابق الفلاتر الحالية</h3><p className="mt-2 text-sm text-slate-500">غيّر الفلاتر أو اختر موظفاً آخر لعرض عمليات مسجلة.</p></div></CardContent></Card>}
  </div>;
}
