import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useAuth } from "@/_core/hooks/useAuth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { CircleAlert, ReceiptText, Target, TrendingUp, UsersRound } from "lucide-react";

const categoryLabels: Record<string, string> = { sales: "المبيعات", operations: "التشغيل", service: "خدمة العملاء", attendance: "الحضور" };
const currency = new Intl.NumberFormat("ar-EG", { style: "currency", currency: "EGP", maximumFractionDigits: 0 });

function MetricCard({ title, value, hint, icon: Icon, tone = "teal" }: { title: string; value: string; hint: string; icon: typeof TrendingUp; tone?: "teal" | "navy" | "amber" | "rose" }) {
  const styles = { teal: "bg-[#e6f5ef] text-[#0f766e]", navy: "bg-[#e8f0f6] text-[#17344a]", amber: "bg-[#fff3db] text-[#b87516]", rose: "bg-[#fff1f2] text-rose-700" };
  return <Card className="border-[#e1ece6] bg-white"><CardContent className="flex items-start justify-between gap-3 p-5"><div><p className="text-xs font-bold text-slate-500">{title}</p><p className="mt-2 text-2xl font-black tracking-tight text-[#17344a]">{value}</p><p className="mt-2 text-xs text-slate-500">{hint}</p></div><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-2xl ${styles[tone]}`}><Icon className="h-5 w-5" /></span></CardContent></Card>;
}

export default function KpiAnalytics() {
  const { user } = useAuth();
  const canView = ["admin", "owner", "manager", "hr_manager"].includes(user?.role ?? "");
  const branches = trpc.organization.listBranches.useQuery(undefined, { enabled: canView });
  const [branchId, setBranchId] = useState<string>("");
  useEffect(() => { if (!branchId && branches.data?.[0]) setBranchId(String(branches.data[0].id)); }, [branchId, branches.data]);
  const data = trpc.analytics.kpiDashboard.useQuery({ branchId: Number(branchId) }, { enabled: canView && Boolean(branchId) });
  const dashboard = data.data;
  const averageScore = dashboard?.categories.length ? Math.round(dashboard.categories.reduce((sum, item) => sum + item.score, 0) / dashboard.categories.length) : 0;
  const currentSales = dashboard?.sales.current;
  const hasSalesDefinitions = (dashboard?.sales.monthly ?? []).some(item => item.sales > 0 || item.invoices > 0);

  if (!canView) return <div dir="rtl" className="rounded-3xl border border-[#dce9e2] bg-white p-8 text-center text-sm text-slate-600">لوحة التحليل متاحة للمالك والمدير ومدير الموارد البشرية فقط.</div>;

  return <div dir="rtl" className="space-y-6">
    <section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#0f766e]">تحليلات الأداء</p><h1 className="mt-1 text-3xl font-black tracking-tight text-[#17344a]">لوحة مؤشرات الأداء</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-slate-500">تابع حضور الفريق ومبيعاته ومتوسط قيمة الفاتورة ونسبة تحقيق الأهداف من سجلات الأداء الفعلية.</p></div><Select value={branchId} onValueChange={setBranchId}><SelectTrigger className="w-56 bg-white"><SelectValue placeholder="اختر الفرع" /></SelectTrigger><SelectContent>{branches.data?.map(branch => <SelectItem key={branch.id} value={String(branch.id)}>{branch.name}</SelectItem>)}</SelectContent></Select></section>
    {data.isLoading ? <div className="grid min-h-64 place-items-center rounded-3xl bg-white text-sm font-bold text-[#0f766e]">جارٍ تحميل مؤشرات الأداء…</div> : null}
    {data.isError ? <Card className="border-rose-200 bg-rose-50"><CardContent className="flex gap-3 p-6 text-sm text-rose-700"><CircleAlert className="h-5 w-5 shrink-0" /><p>تعذر تحميل مؤشرات الأداء لهذا الفرع. تحقق من الاتصال ثم أعد المحاولة.</p></CardContent></Card> : null}
    {dashboard && !data.isError ? <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><MetricCard title="حجم الفريق" value={String(dashboard.teamSize)} hint="موظفون نشطون في الفرع" icon={UsersRound} tone="navy" /><MetricCard title="حضور اليوم" value={`${dashboard.attendance.at(-1)?.present ?? 0} / ${dashboard.teamSize}`} hint="حاضر أو متأخر اليوم" icon={UsersRound} /><MetricCard title="مبيعات الشهر" value={currency.format(currentSales?.sales ?? 0)} hint="من مؤشرات المبيعات المسجلة" icon={TrendingUp} /><MetricCard title="متوسط قيمة الفاتورة" value={currentSales?.invoices ? currency.format(currentSales.averageInvoice) : "—"} hint={currentSales?.invoices ? `${currentSales.invoices} فاتورة مسجلة` : "أضف مؤشر عدد الفواتير"} icon={ReceiptText} tone="amber" /><MetricCard title="تحقيق هدف المبيعات" value={`${currentSales?.targetAchievement ?? 0}٪`} hint="متوسط نتائج مؤشرات المبيعات" icon={Target} tone={(currentSales?.targetAchievement ?? 0) >= 100 ? "teal" : "rose"} /></section>
      {!hasSalesDefinitions ? <Card className="border-amber-200 bg-amber-50"><CardContent className="p-5 text-sm leading-7 text-amber-900"><strong>لا توجد بيانات مبيعات كافية بعد.</strong> عرّف مؤشراً من فئة «المبيعات» بوحدة عملة، ومؤشراً باسم «عدد الفواتير» بوحدة رقمية، ثم سجّل النتائج من وحدة مؤشرات الأداء لتظهر المبيعات ومتوسط الفاتورة بدقة.</CardContent></Card> : null}
      <section className="grid gap-5 xl:grid-cols-2"><Card className="border-[#e1ece6] bg-white"><CardHeader><CardTitle className="text-base text-[#17344a]">المبيعات الشهرية خلال ستة أشهر</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.sales.monthly}><CartesianGrid vertical={false} stroke="#edf3ef" /><XAxis dataKey="month" tick={{ fontSize: 12 }} /><YAxis tickFormatter={value => `${Number(value) / 1000}k`} /><Tooltip formatter={(value: number) => currency.format(value)} labelStyle={{ direction: "rtl" }} /><Bar dataKey="sales" name="المبيعات" fill="#0f766e" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card><Card className="border-[#e1ece6] bg-white"><CardHeader><CardTitle className="text-base text-[#17344a]">متوسط قيمة الفاتورة وتحقيق الهدف</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={dashboard.sales.monthly}><CartesianGrid vertical={false} stroke="#edf3ef" /><XAxis dataKey="month" tick={{ fontSize: 12 }} /><YAxis yAxisId="amount" tickFormatter={value => `${Number(value) / 1000}k`} /><YAxis yAxisId="percentage" orientation="left" domain={[0, 120]} tickFormatter={value => `${value}٪`} /><Tooltip formatter={(value: number, name) => [name === "متوسط الفاتورة" ? currency.format(value) : `${value}٪`, name]} /><Legend /><Line yAxisId="amount" type="monotone" dataKey="averageInvoice" name="متوسط الفاتورة" stroke="#1d4f70" strokeWidth={3} dot={{ r: 4 }} /><Line yAxisId="percentage" type="monotone" dataKey="targetAchievement" name="تحقيق الهدف" stroke="#d38d20" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ResponsiveContainer></CardContent></Card></section>
      <section className="grid gap-5 xl:grid-cols-2"><Card className="border-[#e1ece6] bg-white"><CardHeader><CardTitle className="text-base text-[#17344a]">متوسط الأداء حسب المؤشر</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboard.categories.map(item => ({ ...item, category: categoryLabels[item.category] }))}><CartesianGrid vertical={false} stroke="#edf3ef" /><XAxis dataKey="category" tick={{ fontSize: 12 }} /><YAxis domain={[0, 100]} /><Tooltip formatter={(value: number) => `${value}٪`} /><Bar dataKey="score" name="نسبة الإنجاز" fill="#0f766e" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></CardContent></Card><Card className="border-[#e1ece6] bg-white"><CardHeader><CardTitle className="text-base text-[#17344a]">الحضور خلال سبعة أيام</CardTitle></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={dashboard.attendance}><CartesianGrid vertical={false} stroke="#edf3ef" /><XAxis dataKey="day" tick={{ fontSize: 12 }} /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Line type="monotone" dataKey="present" name="الحضور" stroke="#0f766e" strokeWidth={3} dot={{ r: 4 }} /><Line type="monotone" dataKey="team" name="إجمالي الفريق" stroke="#9ab9ad" strokeDasharray="5 5" /></LineChart></ResponsiveContainer></CardContent></Card></section>
      <Card className="border-[#e1ece6] bg-white"><CardHeader><CardTitle className="flex items-center justify-between gap-3 text-base text-[#17344a]"><span>أفضل نتائج الفريق</span><span className="text-xs font-medium text-slate-400">متوسط الأداء العام: {averageScore}٪</span></CardTitle></CardHeader><CardContent className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={dashboard.employees} margin={{ right: 24 }}><CartesianGrid horizontal={false} stroke="#edf3ef" /><XAxis type="number" domain={[0, 100]} tickFormatter={value => `${value}٪`} /><YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 12 }} /><Tooltip formatter={(value: number) => `${value}٪`} /><Bar dataKey="score" name="نسبة الإنجاز" fill="#1d4f70" radius={[0, 8, 8, 0]} /></BarChart></ResponsiveContainer></CardContent></Card>
    </> : null}
  </div>;
}
