import { useCallback, useEffect, useRef, useState } from "react";
import { MapPin, Navigation, Map as MapIcon } from "lucide-react";
import { MapView } from "@/components/Map";

type Route = { orderId: number; orderCode: string; customerName: string; agentName: string | null; promisedAt: Date | null; points: { latitude: string; longitude: string; accuracyMeters: number | null; capturedAt: Date }[] };

export function DeliveryRouteMap({ routes, onActivate }: { routes: Route[]; onActivate?: () => void }) {
  const mapRef = useRef<google.maps.Map | null>(null); const clearOverlays = useRef<(() => void)[]>([]);
  const [mapRequested, setMapRequested] = useState(false);
  const draw = useCallback(() => { const map = mapRef.current; if (!map || !window.google) return; clearOverlays.current.forEach(clear => clear()); clearOverlays.current = []; const bounds = new google.maps.LatLngBounds();
    routes.forEach((route, index) => { const path = route.points.map(point => ({ lat: Number(point.latitude), lng: Number(point.longitude) })).filter(point => Number.isFinite(point.lat) && Number.isFinite(point.lng)); if (!path.length) return; const color = ["#0f766e", "#2563eb", "#c2410c", "#7c3aed"][index % 4]; const line = new google.maps.Polyline({ path, strokeColor: color, strokeOpacity: .8, strokeWeight: 5, map }); const last = path[path.length - 1]; const marker = new google.maps.marker.AdvancedMarkerElement({ map, position: last, title: `${route.orderCode} · ${route.agentName ?? "مندوب"}` }); clearOverlays.current.push(() => { line.setMap(null); marker.map = null; }); path.forEach(point => bounds.extend(point)); }); if (!bounds.isEmpty()) map.fitBounds(bounds, 72); }, [routes]);
  useEffect(() => { draw(); }, [draw]);
  const activate = () => { setMapRequested(true); onActivate?.(); };
  return <section className="overflow-hidden rounded-3xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="flex items-center gap-2 font-extrabold text-[#17344a]"><Navigation className="h-4 w-4 text-[#0f766e]" /> خريطة الرحلات النشطة</p><p className="mt-1 text-xs text-slate-500">تُحمّل عند طلبها لتسريع شاشة التوصيل، وتعرض المواقع المرسلة خلال «في الطريق» فقط.</p></div><button type="button" onClick={activate} className="inline-flex items-center gap-1 rounded-xl border border-[#cde1d7] bg-[#e6f5ef] px-3 py-2 text-xs font-bold text-[#0f766e]"><MapIcon className="h-3.5 w-3.5" />{mapRequested ? "تحديث الخريطة" : "فتح الخريطة"}</button></div>{mapRequested ? <MapView className="h-[360px]" initialCenter={{ lat: 30.0444, lng: 31.2357 }} initialZoom={10} onMapReady={map => { mapRef.current = map; draw(); }} /> : <div className="grid h-40 place-items-center border-t bg-slate-50 px-4 text-center text-sm text-slate-500">لن يتم تحميل مورد الخرائط أو مواقع الرحلات قبل اختيار «فتح الخريطة».</div>}<div className="grid gap-2 border-t p-4 sm:grid-cols-2">{routes.map(route => { const last = route.points.at(-1); return <div key={route.orderId} className="rounded-2xl bg-slate-50 p-3 text-sm"><p className="font-bold text-[#17344a]"><MapPin className="ml-1 inline h-4 w-4 text-[#0f766e]" />{route.orderCode} · {route.agentName ?? "مندوب"}</p><p className="mt-1 text-xs text-slate-500">{route.customerName}{last ? ` · آخر تحديث ${new Date(last.capturedAt).toLocaleTimeString("ar-EG", { hour: "2-digit", minute: "2-digit" })}` : " · بانتظار أول موقع"}</p></div>; })}{mapRequested && !routes.length ? <p className="text-center text-sm text-slate-500">لا توجد رحلة تتبع نشطة حالياً.</p> : null}</div></section>;
}
