-- Staging only. This migration intentionally creates no production users, branches, files, or credentials.

create type public.staff_role as enum ('owner', 'manager', 'hr_manager', 'pharmacist', 'employee', 'courier');

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (char_length(code) between 1 and 32),
  name text not null check (char_length(name) between 2 and 160),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  branch_id uuid references public.branches(id) on delete cascade,
  role public.staff_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, branch_id, role)
);

create table public.employee_profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  branch_id uuid not null references public.branches(id) on delete restrict,
  employee_code text not null unique check (char_length(employee_code) between 1 and 32),
  full_name text not null check (char_length(full_name) between 2 and 160),
  role public.staff_role not null default 'employee',
  employment_status text not null default 'active' check (employment_status in ('active', 'inactive', 'on_leave')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance_events (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employee_profiles(id) on delete cascade,
  work_date date not null,
  check_in_at timestamptz,
  check_out_at timestamptz,
  worked_minutes integer not null default 0 check (worked_minutes >= 0),
  late_minutes integer not null default 0 check (late_minutes >= 0),
  source text not null default 'self_service' check (source in ('self_service', 'import', 'manual')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (employee_id, work_date)
);

create index employee_profiles_branch_idx on public.employee_profiles(branch_id);
create index app_user_roles_user_branch_idx on public.app_user_roles(user_id, branch_id);
create index attendance_events_employee_date_idx on public.attendance_events(employee_id, work_date desc);

create or replace function public.is_platform_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_user_roles
    where user_id = auth.uid() and role = 'owner'
  );
$$;

create or replace function public.has_branch_access(required_branch_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_owner() or exists (
    select 1 from public.app_user_roles
    where user_id = auth.uid()
      and (branch_id = required_branch_id or branch_id is null)
  );
$$;

create or replace function public.can_manage_branch(required_branch_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_platform_owner() or exists (
    select 1 from public.app_user_roles
    where user_id = auth.uid()
      and role in ('manager', 'hr_manager')
      and (branch_id = required_branch_id or branch_id is null)
  );
$$;

alter table public.branches enable row level security;
alter table public.app_user_roles enable row level security;
alter table public.employee_profiles enable row level security;
alter table public.attendance_events enable row level security;

create policy branches_select_scoped on public.branches for select using (public.has_branch_access(id));
create policy branches_owner_write on public.branches for all using (public.is_platform_owner()) with check (public.is_platform_owner());

create policy roles_select_self_or_owner on public.app_user_roles for select using (user_id = auth.uid() or public.is_platform_owner());
create policy roles_owner_write on public.app_user_roles for all using (public.is_platform_owner()) with check (public.is_platform_owner());

create policy employee_profiles_select_scoped on public.employee_profiles for select using (auth_user_id = auth.uid() or public.has_branch_access(branch_id));
create policy employee_profiles_manage_scoped on public.employee_profiles for all using (public.can_manage_branch(branch_id)) with check (public.can_manage_branch(branch_id));

create policy attendance_events_select_scoped on public.attendance_events for select using (
  exists (select 1 from public.employee_profiles profile where profile.id = employee_id and (profile.auth_user_id = auth.uid() or public.has_branch_access(profile.branch_id)))
);
create policy attendance_events_write_scoped on public.attendance_events for all using (
  exists (select 1 from public.employee_profiles profile where profile.id = employee_id and (profile.auth_user_id = auth.uid() or public.can_manage_branch(profile.branch_id)))
) with check (
  exists (select 1 from public.employee_profiles profile where profile.id = employee_id and (profile.auth_user_id = auth.uid() or public.can_manage_branch(profile.branch_id)))
);
