-- Applied first to Supabase project: pharmacy-people-staging.
-- It creates no employee, payroll, delivery, or customer records.

begin;

create table if not exists public.migration_control (
  id bigint generated by default as identity primary key,
  target text not null unique,
  status text not null check (status in ('planned', 'in_progress', 'validated', 'blocked')),
  notes text not null default '',
  updated_at timestamptz not null default now()
);

-- Deliberately deny browser roles until the migration worker and RBAC policies
-- are reviewed. Service-side migration credentials are never shipped to clients.
alter table public.migration_control enable row level security;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'delivery-proofs',
  'delivery-proofs',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
